model_list:
  - model_name: claude-sonnet
    litellm_params:
      model: openrouter/anthropic/claude-sonnet-5.5:anthropic
      api_key: "os.environ/OPENROUTER_API_KEY"
      max_tokens: 8192
      extra_body:
        include_reasoning: true
        thinking:
          type: "enabled"
          budget_tokens: 2048
      cache_control_injection_points:
        - location: "message"
          role: "system"
          control:
            type: "ephemeral"
            ttl: "1h"

  - model_name: claude-haiku
    litellm_params:
      model: openrouter/anthropic/claude-haiku-5.5:anthropic
      api_key: "os.environ/OPENROUTER_API_KEY"
      max_tokens: 8192
      extra_body:
        include_reasoning: true
        thinking:
          type: "enabled"
          budget_tokens: 2048
      cache_control_injection_points:
        - location: "message"
          role: "system"
          control:
            type: "ephemeral"
            ttl: "1h"

  - model_name: claude-opus
    litellm_params:
      model: openrouter/anthropic/claude-opus-4.7:anthropic
      api_key: "os.environ/OPENROUTER_API_KEY"
      max_tokens: 8192
      extra_body:
        include_reasoning: true
        thinking:
          type: "enabled"
          budget_tokens: 2048
      cache_control_injection_points:
        - location: "message"
          role: "system"
          control:
            type: "ephemeral"
            ttl: "1h"
            
